services:
  data_validator:
    class: RapidAPI\Service\DataValidator
    arguments: []

  sender:
    class: RapidAPI\Service\Sender
    arguments: []

  metadata:
    class: RapidAPI\Service\Metadata
    arguments: []

  manager:
    class: RapidAPI\Service\Manager
    arguments: ["@data_validator", "@metadata","@request_stack"]

  request_parser:
    class: RapidAPI\Service\RequestParser
    arguments: ["@request_stack"]