services:
  data_validator:
    class: ZendeskCoreBundle\Service\DataValidator
    arguments: []

  sender:
    class: ZendeskCoreBundle\Service\Sender
    arguments: []

  metadata:
    class: ZendeskCoreBundle\Service\Metadata
    arguments: []

  manager:
    class: ZendeskCoreBundle\Service\Manager
    arguments: ["@data_validator", "@sender", "@metadata","@request_stack"]