services:
  type_validator:
    class: RapidAPI\Service\TypeValidators\TypeValidator
    arguments: []

  data_validator:
    class: RapidAPI\Service\DataValidator
    arguments: ["@type_validator"]

  generator:
    class: RapidAPI\Service\Generator
    arguments: []

  sender:
    class: RapidAPI\Service\Sender
    arguments: []

  metadata:
    class: RapidAPI\Service\Metadata
    arguments: []

  manager:
    class: RapidAPI\Service\Manager
    arguments: ["@data_validator", "@metadata","@sender", "@generator"]

  request_parser:
    class: RapidAPI\Service\RequestParser
    arguments: ["@request_stack"]